{"name": "test_failure", "status": "failed", "statusDetails": {"message": "AssertionError: assert False", "trace": "@allure.feature('test_failure')\n    def test_failure():\n        \"\"\"this test fails\"\"\"\n>       assert False\nE       assert False\n\nstudy.py:13: AssertionError"}, "description": "this test fails", "start": 1663754643492, "stop": 1663754643492, "uuid": "1f1c8e7a-a649-4f97-9956-8472a1a362ac", "historyId": "70b21e2c8a4d25e493200b1d0a62b218", "testCaseId": "d744e3a1cb80a401615d028c4e4085ef", "fullName": "study#test_failure", "labels": [{"name": "feature", "value": "test_failure"}, {"name": "suite", "value": "study"}, {"name": "host", "value": "CD-N00013"}, {"name": "thread", "value": "6956-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "study"}]}